export const GET_RECIPES = "GET_RECIPES";

export const SEARCH_RECIPES = "SEARCH_RECIPES";

export const ORDER_RECIPES_NAME = "ORDER_RECIPES_NAME";

export const ORDER_RECIPES_HEALTSCORE = "ORDER_RECIPES_HEALTHSCORE";

export const FILTER_RECIPES_DIETS = "FILTER_RECIPES_DIETS";

export const FILTER_RECIPES_ORIGIN = "FILTER_RECIPES_ORIGIN";

export const POST_RECIPE = "POST_RECIPE";

export const DELETE_RECIPE = "DELETE_RECIPE";